AMY <- craschR(scores = AMYwide, itemInfo = AMYitem, consInfo = AMYcons,
               varsInfo = AMYvars, estPackage = "TAM", retainOrig = TRUE,
               consecutive = TRUE, writeout = FALSE)
item.scores(AMY)
pers.hist(AMY)
wm(AMY)
wm(AMY, byCat = TRUE)
ICC.graph(AMY)
CPC.graph(AMY)
CPC.graph(AMY, observed = TRUE, palette = "PuBu")
CPC.graph(AMY, palette = "PuBu")
info.graph(AMY)
info.graph(AMY, type = "IIC")
info.graph(AMY, type = "TIC")
info.graph(AMY, type = "IIC", dim = 1)
info.graph(AMY, dim = 1, type = "TIC", completeOnly = FALSE)
info.graph(AMY, dim = 2)
item.analysis(AMY)
infit.MNSQ(AMY)
infit.MNSQ(AMY, params = "steps")
infit.MNSQ(AMY, itemOrder = c(1,2,4,6,8,10), params = "steps")
KIDMAP(AMY, personID = 131)
KIDMAP(AMY, personID = "131", dim = 2)
